---
- name: Installing Apache on Ubuntu
  hosts: ubuntu
  become: true
  tasks: 
    - name: Install Apache
      apt: pkg=apache2 state=latest update_cache=yes
    - name: enable mod re_write
      apache2_module: name=rewrite state=present  
      notify: 
        - start apache2

  handlers:
    - name: start apache2
      service: name=apache2 state=started
