---
- name: Install NTP
  hosts: local
  gather_facts: true
  become: yes
  become_user: root
  tasks:
   - name: Install common software
     apt: pkg={{ item }} state=installed
     with_items:
       - git
