---
- name: Install common software
  apt: pkg={{ item }} state=installed
  with_items:
    - git
    - htop
    - vim
    - unzip
    - curl

- name: Create sudo group
  group:
    name=sudo
    state=present

- name: Create a new user
  user:
    name={{ user_name }}
    state=present
    groups="sudo"
    shell=/bin/zsh
    password=P@ssw0rd

- name: Create a folder structure
  file: path=/home/{{ user_name }}/{{ item }}
    state=directory
    owner={{ user_name }}
    group={{ user_name }}
    mode=0700
  with_items:
    - src
    - backups
    - bin
    - temp
    - subdir

- name: Copy a file via Ansible
  copy: src={{ item }} dest=/home/{{ user_name }}/{{ item }}
  with_items:
    - test.txt
    - test2.txt
    - test3.txt
